# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

start_profiler <- function(str) {
    .Call('_VEB_Boost_start_profiler', PACKAGE = 'VEB.Boost', str)
}

stop_profiler <- function() {
    .Call('_VEB_Boost_stop_profiler', PACKAGE = 'VEB.Boost')
}

make_stumps_matrix_cpp <- function(X, include_linear, include_stumps, cuts, ncores) {
    .Call('_VEB_Boost_make_stumps_matrix_cpp', PACKAGE = 'VEB.Boost', X, include_linear, include_stumps, cuts, ncores)
}

make_stumps_matrix_sp_cpp <- function(X, include_linear, include_stumps, cuts, ncores) {
    .Call('_VEB_Boost_make_stumps_matrix_sp_cpp', PACKAGE = 'VEB.Boost', X, include_linear, include_stumps, cuts, ncores)
}

weighted_SER_cpp <- function(xp, Y, sigma2, init = NULL, max_lV = 0, lin_prior_prob = 0.5) {
    .Call('_VEB_Boost_weighted_SER_cpp', PACKAGE = 'VEB.Boost', xp, Y, sigma2, init, max_lV, lin_prior_prob)
}

predFnSusieStumps_cpp <- function(xp_new, currentFit, moment) {
    .Call('_VEB_Boost_predFnSusieStumps_cpp', PACKAGE = 'VEB.Boost', xp_new, currentFit, moment)
}

