# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

make_stumps_matrix_cpp <- function(X, include_linear, include_stumps, num_cuts, use_quants, scale_X, ncores) {
    .Call(`_VEB_Boost_make_stumps_matrix_cpp`, X, include_linear, include_stumps, num_cuts, use_quants, scale_X, ncores)
}

make_stumps_matrix_sp_cpp <- function(X, include_linear, include_stumps, num_cuts, use_quants, scale_X, ncores) {
    .Call(`_VEB_Boost_make_stumps_matrix_sp_cpp`, X, include_linear, include_stumps, num_cuts, use_quants, scale_X, ncores)
}

make_stumps_test_matrix_cpp <- function(X, SM_in) {
    .Call(`_VEB_Boost_make_stumps_test_matrix_cpp`, X, SM_in)
}

make_stumps_test_matrix_sp_cpp <- function(X, SM_in) {
    .Call(`_VEB_Boost_make_stumps_test_matrix_sp_cpp`, X, SM_in)
}

weighted_SER_cpp <- function(xp, Y, sigma2, init = NULL, max_lV = 0, lin_prior_prob = 0.5) {
    .Call(`_VEB_Boost_weighted_SER_cpp`, xp, Y, sigma2, init, max_lV, lin_prior_prob)
}

predFnSusieStumps_cpp <- function(xp_new, currentFit, moment) {
    .Call(`_VEB_Boost_predFnSusieStumps_cpp`, xp_new, currentFit, moment)
}

